apiVersion: v1
kind: Service
metadata:
  labels:
  name: cicd-java-maven
  namespace: cicd-java-maven
spec:
 selector:
    app: cicd-java-maven
 ports:
   - protocol: TCP
     port: 8093
     targetPort: 8080
 type: NodePort
